"""create Poll table

Revision ID: b1c3ef91f549
Revises: 9f725c22ebab
Create Date: 2019-05-15 12:14:13.563323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c3ef91f549'
down_revision = '9f725c22ebab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=140), nullable=True),
    sa.Column('field', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll')
    # ### end Alembic commands ###
